name: Continuous Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build project
        uses: sosedoff/actions/golang-build@master
        with:
          args: linux/amd64 darwin/amd64

